<!-- GENERATED BY:  Lectora Online v 6.2.2(227) (http://www.trivantis.com) -->
<!-- TITLE: (Private) Assessing Metacognition -->



var trivstrYA = 'Your answer:'
var trivstrCA = 'Correct answer:'
var trivstrNA = 'Not answered'
var trivstrQ = 'Question '
var trivstrGoToQ = 'Go To Question'
var trivstrFAIL = 'FAILED'
var trivstrPASS = 'PASSED'
var trivstrNG = 'Not Graded'
var trivstrSCORE = 'SCORE:'
var trivstrSTUD = 'Student:'
var trivstrTRSUB = 'Your test results have been submitted.'
var trivstrSUSUB = 'Your survey responses have been submitted.'
var trivstrOK = 'OK'
var trivstrCancel = 'Cancel'
var trivstrPrint = 'Print'
var trivstrDetails = 'Details'
var trivstrCMTO = 'Your session has timed out. Please login again.'
var trivstrERRNQ = 'The number of questions in the test has changed. Please contact your instructor to reset the test results.'
var trivstrERRAS = 'You have already submitted the results of this test.'
var trivstrERRLI = 'You must be properly logged in to CourseMill to submit this test.'
var trivstrERRST = 'There was an error submitting your test results, please try again later.'
var trivstrERRAICC = 'Unable to contact AICC Course Management System.<br>This course must be run from within an AICC Course Management System for the course data to be recorded.'
var trivstrERRIO = 'I/O Error, cannot send results:'
var trivstrERRMU = 'MalformedURL Exception! '
var trivstrERRSE = 'Security Error, unable to send request.<br>This course must be loaded from the system that the data is submitted to:'
var trivstrERRUH = 'Unable to find local host, cannot send results:'
var trivstrCOR = 'Correct'
var trivstrINC = 'Incorrect'
var trivstrLKP = 'Link to question'
var trivstrLKF = 'Link to first page in test'
var trivstrCOVT = 'Correct-over-total count:'
var trivstrFBTR = 'Feedback:'
var trivstrPSCO = 'Lowest passing score:'
var trivstrSEL = 'Selected'
var trivstrNOSEL = 'Not selected'
var trivstrBGNCR = 'Tap / click here to continue.'
var trivstrRMDROPS = 'The drag item limit for this question is ##0 in each drop zone. Remove an item to change entries.'
var trivstrSTATNS = 'Not Started'
var trivstrSTATIP = 'In Progress'
var trivstrSTATC = 'Completed'
var trivstrCHAPTER = 'Chapter'
var trivstrSECTION = 'Section'
var trivstrPAGE = 'Page'
var trivstrTEST = 'Test'
var trivstrSURVEY = 'Survey'
var trivstrTESTSECTION = 'Test Section'
var trivstrAnd = 'and'
var trivstrOr = 'or'
var trivstrCloseWindow = 'Close'
var trivstrUpdate = 'Update';
var trivstrRefresh = 'Refresh';
var trivstrClose = 'Close';
var trivstrVariables = 'Variables';
var trivstrClear = 'Clear';
var trivstrErrLoadTestServer = 'You must run this content from a web-based server [##0]: ##1';
var trivstrErrLoadTestXml = 'Unable to process test [##0] because of an XML parse error.';
var trivstrPopBlock = 'Please disable any popup blockers.';

/* publish options

Publish Type: HTML 
Create ALT tags for images and buttons: Yes 
Convert page names to short ID-based names: Yes 
Use Lightbox pop ups: Yes 
Optimize published image sizes: Yes 
Publish for Seamless Play: Yes 
Protect content: Yes 
Disable browser resize of published content: Yes 
Scale content to fill window: Yes 
Fit content to width: No 
Scale content to fill mobile device view: Yes 

{"bFTPTitle":0,"bCreateAltTags":true,"bPENSTitle":false,"bPartialPublish":false,"bCourseMillTitle":false,"bAICCTitle":false,"bSCORMTitle":false,"bSumTotalTitle":false,"bPWCTitle":false,"bMoodleTitle":false,"bWebCTTitle":false,"bCopyPlayer":true,"bPublishToRepository":false,"bPublishUpdated":true,"bIncTitleMgr":false,"dwParmFlags":1305088,"htmlIndexFile":"index.html","scaleLimitWidth":"","publishZipFile":"","strEncryptPassword":"","strIconFilename":"","strINI":"","iDebugOptions":31,"ftpParms":{"HostName":"","UserID":"","Password":"","InitialDir":"","transferMode":"passive"},"PENSParms":{"ClientNamespace":"","TargetSystemURL":"","PensVersion":"","PackageType":"","PackageTypeFormat":"","PackageID":"","PackageURL":"","PackageURLExpiry":"","Client":"","UserID":"","Password":"","Receipt":"","Alerts":"","EmailAddr":""},"coursemillParms":{"Name":"","Course":"","Instructor":"","Password":"","Error":"","ErrorCode":0,"Version":0},"aiccParms":{"CourseCreator":"","CourseID":"","CourseSystem":"","CourseTitle":"","CourseWebLocation":"","CourseLevel":0,"CourseMaxFieldsCST":0,"CourseTotalAUs":0,"CourseTotalBlocks":0,"CourseVersion":"","BehaviorMaxNormal":0,"CourseDescription":"","bSameDomain":false,"bForceCloseContent":false,"bHandleInteractions":false,"bBookmarking":false,"bTrackProgress":false,"bUseAUValues":false,"CourseSystemID":"","DeveloperID":"","CourseType":"","MasteryScore":"","MaxTimeAllowed":0,"strMTA":"","TimeLimitAction":0,"strDefaultMasteryScore":"75","strMaxScore":"100"},"scormParms":{"Keywords":"","Version":0},"bGeneratePageNames":true,"chkSaba":false}

*/

